Itay/ex5
itayneu/monday-u-exercises pull request #6
Opened 2022-06-23 18:06 UTC by itayneu

2022-06-29 16:45 UTC, SergeiSafrigin requested changes
Good job! Overall it looks good!
Keep:
- A good improvement in separation of concerns 💪

Improve:
- A bit more emphasis on the UI/UX will skyrocket your app 😁
- Make sure the app works and running out of the box (if a running MySQL via docker is required, kindly add the instructions to the readme file)

2022-06-29 16:45 UTC, SergeiSafrigin commented on src/dist/main.js
> +    const itemsList = await this.itemClient.getItems();
avoid fetching all the items per item update/add

2022-06-29 16:45 UTC, SergeiSafrigin commented on src/dist/main.js
> +    item.status = !item.status;
add a separate functions for updating status (which will call this method)

2022-06-29 16:45 UTC, SergeiSafrigin commented on src/dist/main.js
> +      const listItemCheckbox = this._createCheckbox(item);
extract the createItemElement logic to a different function

2022-06-29 16:45 UTC, SergeiSafrigin commented on src/dist/main.js
> +          ).toLocaleString()})`
consider using a different technique for showing the done date (tooltip? title dom attribute?)

2022-06-29 16:45 UTC, SergeiSafrigin commented on src/server/db/config/config.json
> +  },
like!

2022-06-29 16:45 UTC, SergeiSafrigin commented on src/server/db/migrations/20220618101015-create-items.js
> +      itemName: {
consider changing to name

2022-06-29 16:45 UTC, SergeiSafrigin commented on src/server/services/item_manager.js
> +  console.log("input", input);
remove

2022-06-29 16:45 UTC, SergeiSafrigin commented on src/server/services/item_manager.js
> +  await Items.update(
separate the business logic ("flow-manager") from the data access layer logic

2022-06-29 16:45 UTC, SergeiSafrigin commented on src/server/services/item_manager.js
> +    handlePokemonItem(inputString);
consider changing to a more descriptive name + more different from addPokemonItem

2022-06-29 16:45 UTC, SergeiSafrigin commented on src/server/services/item_manager.js
> +    handleNormalItem(inputString);
textItem/ baseItem

2022-06-29 16:46 UTC, SergeiSafrigin commented on src/server/routes/todoRouter.js
>  todoRouter.get("/items", getItems);
server.js is not in the changelist, but don't forget to fix the static path that serves the dist folder

2022-07-01 13:03 UTC, itayneu commented on src/dist/main.js
> +    item.status = !item.status;
Done

2022-07-07 16:35 UTC, closed without merging